key,default_value
userAgent,"Boto3/1.9.39 Python/2.7.16 Linux/4.19.0-kali5-amd64 Botocore/1.12.86"
eventID,"ea042b49-74cc-4f42-a9db-bdea7c0142a1"
errorMessage,"An unknown error occurred"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDADO2GQD0K8TEF7KW1V"
userIdentity_arn,"arn:aws:iam::811596193553:user/Level6"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA3Z2XBVUDFQ9TU4MD"
userIdentity_userName,"Level6"
eventType,"AwsApiCall"
errorCode,"AccessDeniedException"
sourceIPAddress,"248.251.245.4"
eventName,"GetDataCatalogEncryptionSettings"
eventSource,"glue.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"4fe40c91-aec0-11e9-8161-3f54dd9f8cea"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2019-07-25T09:41:00Z"
