key,default_value
userAgent,"Boto3/1.7.4 Python/3.6.6 Linux/4.16.0-kali2-amd64 Botocore/1.10.4"
eventID,"6312b79f-f7d9-403c-95e5-1f1c8bfbd0f5"
errorMessage,"An unknown error occurred"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDADO2GQD0K8TEF7KW1V"
userIdentity_arn,"arn:aws:iam::811596193553:user/Level6"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA3Z2XBVUDFQ9TU4MD"
userIdentity_userName,"Level6"
eventType,"AwsApiCall"
errorCode,"AccessDeniedException"
sourceIPAddress,"9.245.1.85"
eventName,"GetDatabases"
eventSource,"glue.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"0a5ea46a-d54e-11e8-92a9-c17993f93cb7"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2018-10-21T16:26:19Z"
