key,default_value
userAgent,"Botocore/1.12.25 Python/2.7.15 Linux/4.16.0-kali2-amd64"
eventID,"3457e4b9-b98b-415a-8a32-69ae2270e933"
errorMessage,"An unknown error occurred"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDADO2GQD0K8TEF7KW1V"
userIdentity_arn,"arn:aws:iam::811596193553:user/Level6"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA3Z2XBVUDFQ9TU4MD"
userIdentity_userName,"Level6"
eventType,"AwsApiCall"
errorCode,"InternalFailure"
sourceIPAddress,"9.245.1.85"
eventName,"ListTasks"
eventSource,"ecs.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-east-1"
requestID,"654521cca-d249-11e8-8391-1574daafb174"
responseElements,"None"
eventVersion,"1.04"
eventTime,"2018-10-17T20:15:32Z"
