key,default_value
additionalEventData_SignatureVersion,"SigV4"
additionalEventData_CipherSuite,"ECDHE-RSA-AES128-GCM-SHA256"
additionalEventData_AuthenticationMethod,"AuthHeader"
userAgent,"[Boto3/1.4.7 Python/2.7.15rc1 Linux/4.15.0-1035-aws Botocore/1.7.48]"
eventID,"97f9c0f7-c285-4653-b6bb-313e676c21ef"
errorMessage,"Access Denied"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"107.164.125.91"
eventName,"PutBucketNotification"
eventSource,"s3.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters_notification_0,""
requestParameters_bucketName,"flaws.cloud"
requestParameters_NotificationConfiguration_xmlns,"http://s3.amazonaws.com/doc/2006-03-01/"
requestParameters_NotificationConfiguration_TopicConfiguration_Event,"s3:ReducedRedundancyLostObject"
requestParameters_NotificationConfiguration_TopicConfiguration_Topic,"arn:aws:sns:us-west-2:005412338514:sns-topic-one"
requestParameters_host_0,"s3.us-west-2.amazonaws.com"
awsRegion,"us-west-2"
requestID,"E1347D268AA5D801"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2019-05-07T15:07:02Z"
